# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_man_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MangerLogin(object):
    def setupUi(self, MangerLogin):
        MangerLogin.setObjectName("MangerLogin")
        MangerLogin.resize(621, 477)
        MangerLogin.setStyleSheet("QPushButton:hover{\n"
"        color:red\n"
"        }\n"
"QLineEdit{\n"
"        border:1px solid gray;;\n"
"        border-radius:10px;\n"
"        padding:2px 4px;\n"
"}\n"
"QWidget{\n"
"        color:#0c0a0a;\n"
"        background:rgb(255, 255, 253);\n"
"        border-top:1px solid darkGray;\n"
"        border-bottom:1px solid darkGray;\n"
"        border-right:1px solid darkGray;\n"
"        border-left:1px solid darkGray;\n"
"        border-top-left-radius:10px;\n"
"        border-top-right-radius:10px;\n"
"        border-bottom-right-radius:10px;\n"
"        border-bottom-left-radius:10px;\n"
"    }\n"
"QLabel{\n"
"        border:none;}\n"
"\n"
"")
        self.widget = QtWidgets.QWidget(MangerLogin)
        self.widget.setGeometry(QtCore.QRect(70, 20, 491, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.id_line = QtWidgets.QLineEdit(self.widget)
        self.id_line.setMinimumSize(QtCore.QSize(230, 30))
        self.id_line.setMaximumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.id_line.setFont(font)
        self.id_line.setStyleSheet("QLineEdit{\n"
"    font-size:16px;\n"
"    border:none;\n"
"    border-bottom:1px solid lightgray;\n"
"    background-color:transparent;\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QLineEdit:hover{\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom:1px solid rgb(18,183,245);\n"
"}\n"
"")
        self.id_line.setText("")
        self.id_line.setFrame(True)
        self.id_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.id_line.setClearButtonEnabled(True)
        self.id_line.setObjectName("id_line")
        self.horizontalLayout.addWidget(self.id_line)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.password_line = QtWidgets.QLineEdit(self.widget)
        self.password_line.setMinimumSize(QtCore.QSize(230, 30))
        self.password_line.setMaximumSize(QtCore.QSize(230, 30))
        self.password_line.setStyleSheet("QLineEdit{\n"
"    font-size:16px;\n"
"    border:none;\n"
"    border-bottom:1px solid lightgray;\n"
"    background-color:transparent;\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QLineEdit:hover{\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom:1px solid rgb(18,183,245);\n"
"}\n"
"")
        self.password_line.setText("")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setClearButtonEnabled(True)
        self.password_line.setObjectName("password_line")
        self.horizontalLayout_2.addWidget(self.password_line)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.okButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_4.setBuddy(self.id_line)
        self.label_2.setBuddy(self.password_line)

        self.retranslateUi(MangerLogin)
        QtCore.QMetaObject.connectSlotsByName(MangerLogin)

    def retranslateUi(self, MangerLogin):
        _translate = QtCore.QCoreApplication.translate
        MangerLogin.setWindowTitle(_translate("MangerLogin", "管理员登陆"))
        self.label_3.setText(_translate("MangerLogin", "管理员登录"))
        self.label_4.setText(_translate("MangerLogin", "账号："))
        self.id_line.setPlaceholderText(_translate("MangerLogin", "请输入您的账号"))
        self.label_2.setText(_translate("MangerLogin", "密码："))
        self.password_line.setPlaceholderText(_translate("MangerLogin", "请输入您的密码"))
        self.okButton.setText(_translate("MangerLogin", "确认登录"))
