# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_bookinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(712, 427)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(144, 24))
        Dialog.setStyleSheet("QPushButton:hover{\n"
"        color:red;\n"
"        font: 10pt \"Arial\";\n"
"        }\n"
"QLineEdit{\n"
"        border:1px solid gray;;\n"
"        border-radius:10px;\n"
"        padding:2px 4px;\n"
"}\n"
"QWidget{\n"
"        color:#0c0a0a;\n"
"        background:rgb(255, 255, 254);\n"
"        border-top:1px solid darkGray;\n"
"        border-bottom:1px solid darkGray;\n"
"        border-right:1px solid darkGray;\n"
"        border-left:1px solid darkGray;\n"
"        border-top-left-radius:10px;\n"
"        border-top-right-radius:10px;\n"
"        border-bottom-right-radius:10px;\n"
"        border-bottom-left-radius:10px;\n"
"    }\n"
"QLabel{\n"
"        border:none;}\n"
"\n"
"QTextBrowser{border:none}\n"
"QPushButton{border:none}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setMinimumSize(QtCore.QSize(260, 350))
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton)
        self.price_Browser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_Browser.sizePolicy().hasHeightForWidth())
        self.price_Browser.setSizePolicy(sizePolicy)
        self.price_Browser.setMaximumSize(QtCore.QSize(16777215, 30))
        self.price_Browser.setObjectName("price_Browser")
        self.verticalLayout_2.addWidget(self.price_Browser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.booknameBrowser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booknameBrowser.sizePolicy().hasHeightForWidth())
        self.booknameBrowser.setSizePolicy(sizePolicy)
        self.booknameBrowser.setMinimumSize(QtCore.QSize(200, 50))
        self.booknameBrowser.setMaximumSize(QtCore.QSize(200, 50))
        self.booknameBrowser.setObjectName("booknameBrowser")
        self.horizontalLayout_4.addWidget(self.booknameBrowser)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.bookauthor_Browser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookauthor_Browser.sizePolicy().hasHeightForWidth())
        self.bookauthor_Browser.setSizePolicy(sizePolicy)
        self.bookauthor_Browser.setMinimumSize(QtCore.QSize(200, 50))
        self.bookauthor_Browser.setMaximumSize(QtCore.QSize(200, 50))
        self.bookauthor_Browser.setObjectName("bookauthor_Browser")
        self.horizontalLayout_3.addWidget(self.bookauthor_Browser)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.bookpress_Browser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookpress_Browser.sizePolicy().hasHeightForWidth())
        self.bookpress_Browser.setSizePolicy(sizePolicy)
        self.bookpress_Browser.setMinimumSize(QtCore.QSize(200, 35))
        self.bookpress_Browser.setMaximumSize(QtCore.QSize(200, 35))
        self.bookpress_Browser.setObjectName("bookpress_Browser")
        self.horizontalLayout_2.addWidget(self.bookpress_Browser)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.booknoteBrowser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booknoteBrowser.sizePolicy().hasHeightForWidth())
        self.booknoteBrowser.setSizePolicy(sizePolicy)
        self.booknoteBrowser.setMinimumSize(QtCore.QSize(200, 80))
        self.booknoteBrowser.setMaximumSize(QtCore.QSize(200, 80))
        self.booknoteBrowser.setOpenExternalLinks(True)
        self.booknoteBrowser.setOpenLinks(True)
        self.booknoteBrowser.setObjectName("booknoteBrowser")
        self.horizontalLayout.addWidget(self.booknoteBrowser)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem13 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.pur_spinBox = QtWidgets.QSpinBox(Dialog)
        self.pur_spinBox.setMinimumSize(QtCore.QSize(80, 30))
        self.pur_spinBox.setMaximum(1000)
        self.pur_spinBox.setObjectName("pur_spinBox")
        self.horizontalLayout_5.addWidget(self.pur_spinBox)
        self.cart_Button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cart_Button.sizePolicy().hasHeightForWidth())
        self.cart_Button.setSizePolicy(sizePolicy)
        self.cart_Button.setMinimumSize(QtCore.QSize(100, 30))
        self.cart_Button.setObjectName("cart_Button")
        self.horizontalLayout_5.addWidget(self.cart_Button)
        spacerItem15 = QtWidgets.QSpacerItem(13, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.pur_Button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pur_Button.sizePolicy().hasHeightForWidth())
        self.pur_Button.setSizePolicy(sizePolicy)
        self.pur_Button.setMinimumSize(QtCore.QSize(100, 30))
        self.pur_Button.setObjectName("pur_Button")
        self.horizontalLayout_5.addWidget(self.pur_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "图书信息浏览"))
        self.toolButton.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "书名"))
        self.label_2.setText(_translate("Dialog", "作者"))
        self.label_3.setText(_translate("Dialog", "出版社"))
        self.label_4.setText(_translate("Dialog", "简介"))
        self.cart_Button.setText(_translate("Dialog", "加入购物车"))
        self.pur_Button.setText(_translate("Dialog", "立即购买"))
